// GENERATED FILE — do not edit by hand. Run `pnpm generate-icons`.

export const ICON_IDS = [
  'fork-knife',
  'bowl-food',
  'bowl-steam',
  'cooking-pot',
  'pizza',
  'hamburger',
  'bread',
  'cookie',
  'cake',
  'ice-cream',
  'popcorn',
  'coffee',
  'tea-bag',
  'cheers',
  'beer-stein',
  'wine',
  'martini',
  'carrot',
  'orange',
  'avocado',
  'grains',
  'fish',
  'egg',
  'shrimp',
  'pepper',
  'knife',
  'shopping-cart',
  'shopping-bag',
  'basket',
  'storefront',
  'bag',
  'tag',
  'tag-chevron',
  't-shirt',
  'hoodie',
  'pants',
  'dress',
  'sneaker',
  'high-heel',
  'eyeglasses',
  'sunglasses',
  'watch',
  'diamond',
  'scissors',
  'sparkle',
  'package',
  'truck',
  'house',
  'house-line',
  'building-apartment',
  'city',
  'bed',
  'couch',
  'armchair',
  'dresser',
  'lamp',
  'door-open',
  'key',
  'keyhole',
  'oven',
  'washing-machine',
  'bathtub',
  'shower',
  'toilet',
  'broom',
  'hammer',
  'wrench',
  'screwdriver',
  'toolbox',
  'paint-roller',
  'paint-brush-household',
  'trash',
  'elevator',
  'stairs',
  'lightning',
  'plug-charging',
  'solar-panel',
  'lightbulb',
  'drop',
  'fire',
  'thermometer',
  'wifi-high',
  'cell-tower',
  'broadcast',
  'phone',
  'television-simple',
  'monitor',
  'laptop',
  'desktop-tower',
  'printer',
  'cloud',
  'hard-drives',
  'mailbox',
  'newspaper',
  'pipe',
  'car',
  'car-profile',
  'taxi',
  'bus',
  'train',
  'tram',
  'bicycle',
  'scooter',
  'gas-pump',
  'steering-wheel',
  'garage',
  'traffic-cone',
  'traffic-sign',
  'road-horizon',
  'map-pin',
  'airplane-takeoff',
  'boat',
  'heartbeat',
  'stethoscope',
  'pill',
  'prescription',
  'syringe',
  'bandaids',
  'first-aid-kit',
  'hospital',
  'brain',
  'eye',
  'tooth',
  'barbell',
  'person-simple-run',
  'virus',
  'graduation-cap',
  'student',
  'book-open',
  'books',
  'notebook',
  'note-pencil',
  'pencil-ruler',
  'backpack',
  'chalkboard-teacher',
  'exam',
  'certificate',
  'translate',
  'microscope',
  'ruler',
  'game-controller',
  'film-slate',
  'film-strip',
  'music-notes',
  'headphones',
  'guitar',
  'microphone-stage',
  'mask-happy',
  'ticket',
  'palette',
  'camera',
  'dice-five',
  'puzzle-piece',
  'basketball',
  'soccer-ball',
  'swimming-pool',
  'beach-ball',
  'tent',
  'mountains',
  'tree-palm',
  'island',
  'suitcase-rolling',
  'suitcase',
  'compass',
  'globe',
  'map-trifold',
  'sun',
  'moon-stars',
  'binoculars',
  'baby',
  'baby-carriage',
  'users-three',
  'user',
  'handshake',
  'hand-heart',
  'heart',
  'gift',
  'confetti',
  'flower',
  'dog',
  'cat',
  'paw-print',
  'bone',
  'mosque',
  'church',
  'star-and-crescent',
  'cigarette',
  'briefcase',
  'office-chair',
  'presentation-chart',
  'chart-line-up',
  'chart-line-down',
  'chart-bar',
  'chart-pie-slice',
  'chart-donut',
  'trend-up',
  'trend-down',
  'percent',
  'rocket-launch',
  'target',
  'flag',
  'trophy',
  'medal',
  'star',
  'crown-simple',
  'wallet',
  'piggy-bank',
  'coins',
  'hand-coins',
  'money',
  'money-wavy',
  'credit-card',
  'cardholder',
  'bank',
  'vault',
  'receipt',
  'invoice',
  'calculator',
  'currency-circle-dollar',
  'currency-dollar',
  'currency-eur',
  'currency-gbp',
  'currency-btc',
  'hand-deposit',
  'hand-arrow-up',
  'umbrella',
  'shield-check',
  'scales',
  'gavel',
  'file-text',
  'scroll',
  'stamp',
  'clipboard-text',
  'calendar-dots',
  'calendar-check',
  'clock',
  'alarm',
  'repeat',
  'arrows-clockwise',
  'seal-check',
  'leaf',
  'plant',
  'tree',
  'tree-evergreen',
  'recycle',
  'flower-lotus',
  'folder',
  'folders',
  'stack',
  'archive',
  'bookmark',
  'grid-four',
  'list',
  'dots-three-circle',
  'question',
  'circles-three',
  'squares-four',
  'note',
] as const

export type IconId = (typeof ICON_IDS)[number]

export type IconGroupKey =
  | 'food'
  | 'shopping'
  | 'home'
  | 'bills'
  | 'transport'
  | 'health'
  | 'education'
  | 'leisure'
  | 'travel'
  | 'family'
  | 'work'
  | 'money'
  | 'admin'
  | 'nature'
  | 'other'

export type IconGroup = {
  readonly key: IconGroupKey
  readonly label: string
  readonly ids: readonly IconId[]
}

export const ICON_GROUPS: readonly IconGroup[] = [
  {
    key: 'food',
    label: 'Food & drink',
    ids: [
      'fork-knife',
      'bowl-food',
      'bowl-steam',
      'cooking-pot',
      'pizza',
      'hamburger',
      'bread',
      'cookie',
      'cake',
      'ice-cream',
      'popcorn',
      'coffee',
      'tea-bag',
      'cheers',
      'beer-stein',
      'wine',
      'martini',
      'carrot',
      'orange',
      'avocado',
      'grains',
      'fish',
      'egg',
      'shrimp',
      'pepper',
      'knife',
    ],
  },
  {
    key: 'shopping',
    label: 'Shopping',
    ids: [
      'shopping-cart',
      'shopping-bag',
      'basket',
      'storefront',
      'bag',
      'tag',
      'tag-chevron',
      't-shirt',
      'hoodie',
      'pants',
      'dress',
      'sneaker',
      'high-heel',
      'eyeglasses',
      'sunglasses',
      'watch',
      'diamond',
      'scissors',
      'sparkle',
      'package',
      'truck',
    ],
  },
  {
    key: 'home',
    label: 'Home',
    ids: [
      'house',
      'house-line',
      'building-apartment',
      'city',
      'bed',
      'couch',
      'armchair',
      'dresser',
      'lamp',
      'door-open',
      'key',
      'keyhole',
      'oven',
      'washing-machine',
      'bathtub',
      'shower',
      'toilet',
      'broom',
      'hammer',
      'wrench',
      'screwdriver',
      'toolbox',
      'paint-roller',
      'paint-brush-household',
      'trash',
      'elevator',
      'stairs',
    ],
  },
  {
    key: 'bills',
    label: 'Bills & utilities',
    ids: [
      'lightning',
      'plug-charging',
      'solar-panel',
      'lightbulb',
      'drop',
      'fire',
      'thermometer',
      'wifi-high',
      'cell-tower',
      'broadcast',
      'phone',
      'television-simple',
      'monitor',
      'laptop',
      'desktop-tower',
      'printer',
      'cloud',
      'hard-drives',
      'mailbox',
      'newspaper',
      'pipe',
    ],
  },
  {
    key: 'transport',
    label: 'Transport',
    ids: [
      'car',
      'car-profile',
      'taxi',
      'bus',
      'train',
      'tram',
      'bicycle',
      'scooter',
      'gas-pump',
      'steering-wheel',
      'garage',
      'traffic-cone',
      'traffic-sign',
      'road-horizon',
      'map-pin',
      'airplane-takeoff',
      'boat',
    ],
  },
  {
    key: 'health',
    label: 'Health',
    ids: [
      'heartbeat',
      'stethoscope',
      'pill',
      'prescription',
      'syringe',
      'bandaids',
      'first-aid-kit',
      'hospital',
      'brain',
      'eye',
      'tooth',
      'barbell',
      'person-simple-run',
      'virus',
    ],
  },
  {
    key: 'education',
    label: 'Education',
    ids: [
      'graduation-cap',
      'student',
      'book-open',
      'books',
      'notebook',
      'note-pencil',
      'pencil-ruler',
      'backpack',
      'chalkboard-teacher',
      'exam',
      'certificate',
      'translate',
      'microscope',
      'ruler',
    ],
  },
  {
    key: 'leisure',
    label: 'Leisure',
    ids: [
      'game-controller',
      'film-slate',
      'film-strip',
      'music-notes',
      'headphones',
      'guitar',
      'microphone-stage',
      'mask-happy',
      'ticket',
      'palette',
      'camera',
      'dice-five',
      'puzzle-piece',
      'basketball',
      'soccer-ball',
      'swimming-pool',
      'beach-ball',
    ],
  },
  {
    key: 'travel',
    label: 'Travel',
    ids: [
      'tent',
      'mountains',
      'tree-palm',
      'island',
      'suitcase-rolling',
      'suitcase',
      'compass',
      'globe',
      'map-trifold',
      'sun',
      'moon-stars',
      'binoculars',
    ],
  },
  {
    key: 'family',
    label: 'Family & giving',
    ids: [
      'baby',
      'baby-carriage',
      'users-three',
      'user',
      'handshake',
      'hand-heart',
      'heart',
      'gift',
      'confetti',
      'flower',
      'dog',
      'cat',
      'paw-print',
      'bone',
      'mosque',
      'church',
      'star-and-crescent',
      'cigarette',
    ],
  },
  {
    key: 'work',
    label: 'Work & growth',
    ids: [
      'briefcase',
      'office-chair',
      'presentation-chart',
      'chart-line-up',
      'chart-line-down',
      'chart-bar',
      'chart-pie-slice',
      'chart-donut',
      'trend-up',
      'trend-down',
      'percent',
      'rocket-launch',
      'target',
      'flag',
      'trophy',
      'medal',
      'star',
      'crown-simple',
    ],
  },
  {
    key: 'money',
    label: 'Money & accounts',
    ids: [
      'wallet',
      'piggy-bank',
      'coins',
      'hand-coins',
      'money',
      'money-wavy',
      'credit-card',
      'cardholder',
      'bank',
      'vault',
      'receipt',
      'invoice',
      'calculator',
      'currency-circle-dollar',
      'currency-dollar',
      'currency-eur',
      'currency-gbp',
      'currency-btc',
      'hand-deposit',
      'hand-arrow-up',
    ],
  },
  {
    key: 'admin',
    label: 'Admin & obligations',
    ids: [
      'umbrella',
      'shield-check',
      'scales',
      'gavel',
      'file-text',
      'scroll',
      'stamp',
      'clipboard-text',
      'calendar-dots',
      'calendar-check',
      'clock',
      'alarm',
      'repeat',
      'arrows-clockwise',
      'seal-check',
    ],
  },
  {
    key: 'nature',
    label: 'Nature',
    ids: ['leaf', 'plant', 'tree', 'tree-evergreen', 'recycle', 'flower-lotus'],
  },
  {
    key: 'other',
    label: 'Other',
    ids: [
      'folder',
      'folders',
      'stack',
      'archive',
      'bookmark',
      'grid-four',
      'list',
      'dots-three-circle',
      'question',
      'circles-three',
      'squares-four',
      'note',
    ],
  },
]

const KNOWN: ReadonlySet<string> = new Set(ICON_IDS)

export const isIconId = (value: unknown): value is IconId =>
  typeof value === 'string' && KNOWN.has(value)
