/**
 * Row builders for the planned slice's tests. Test-only: nothing in the app imports this.
 */
import type {
  LocalBalanceNode,
  LocalBill,
  LocalGoal,
  LocalIncomeStream,
  LocalPlanned,
  LocalSetAside,
  LocalTransaction,
} from '#/db/types'
import { catId } from '#/features/categories/__fixtures__/categories'

let seq = 0
const next = (prefix: string) => `${prefix}${++seq}`

/** SAR/USD carry two minor digits, so whole amounts scale by 100. */
export const m = (whole: number) => whole * 100

export const RATES: Partial<Record<string, number>> = { SAR: 1, USD: 3.75 }

export const goal = (over: Partial<LocalGoal> = {}): LocalGoal => ({
  id: next('g'),
  name: 'Goal',
  currency: 'SAR',
  color: '#EC4899',
  position: 0,
  target: null,
  amount: null,
  dueDate: null,
  mustHave: false,
  saveWalletId: null,
  useCategoryId: null,
  closedAt: null,
  pausedAt: null,
  plannedAt: null,
  planAmount: null,
  planCount: null,
  planStart: null,
  setAsideDay: null,
  createdAt: '',
  updatedAt: '',
  version: '',
  dirty: 0,
  deleted: 0,
  ...over,
})

export const income = (
  over: Partial<LocalIncomeStream> = {},
): LocalIncomeStream => ({
  id: next('i'),
  label: 'Salary',
  amount: 0,
  currency: 'SAR',
  frequency: 'monthly',
  customInterval: null,
  customUnit: null,
  day: 27,
  anchorDate: null,
  endsOn: null,
  color: '#1F9D6B',
  position: 0,
  walletId: null,
  categoryId: catId('salary'),
  merchantId: null,
  autolog: false,
  note: null,
  createdAt: '',
  updatedAt: '',
  version: '',
  dirty: 0,
  deleted: 0,
  ...over,
})

export const bill = (over: Partial<LocalBill> = {}): LocalBill => ({
  id: next('b'),
  name: 'Rent',
  amount: m(3000),
  currency: 'SAR',
  frequency: 'monthly',
  customInterval: null,
  customUnit: null,
  nextDue: '2026-10-01',
  endsOn: null,
  walletId: 'w1',
  saveWalletId: null,
  categoryId: catId('housing'),
  merchantId: null,
  note: null,
  autopay: false,
  mustPay: true,
  color: '#8B5CF6',
  position: 0,
  closedAt: null,
  plannedAt: null,
  planAmount: null,
  planCount: null,
  planStart: null,
  setAsideDay: null,
  createdAt: '',
  updatedAt: '',
  version: '',
  dirty: 0,
  deleted: 0,
  ...over,
})

export const wallet = (
  over: Partial<LocalBalanceNode> = {},
): LocalBalanceNode => ({
  id: next('w'),
  kind: 'wallet',
  parentId: null,
  name: 'Main Checking',
  color: '#1F9D6B',
  icon: null,
  note: null,
  position: 0,
  collapsed: false,
  archivedAt: null,
  amount: 0,
  currency: 'SAR',
  createdAt: '',
  updatedAt: '',
  version: '',
  dirty: 0,
  deleted: 0,
  ...over,
})

export const planned = (over: Partial<LocalPlanned> = {}): LocalPlanned => ({
  id: next('p'),
  origin: 'goal',
  role: 'set_aside',
  goalId: 'g',
  incomeStreamId: null,
  billId: null,
  walletId: null,
  name: 'Goal set-aside',
  amount: m(1500),
  currency: 'SAR',
  categoryId: null,
  occurrence: '2026-10-01',
  date: over.occurrence ?? '2026-10-01',
  status: 'open',
  pinned: false,
  review: false,
  note: null,
  createdAt: '',
  updatedAt: '',
  version: '',
  dirty: 0,
  deleted: 0,
  ...over,
})

export const tx = (over: Partial<LocalTransaction> = {}): LocalTransaction => ({
  id: next('t'),
  type: 'spend',
  amount: m(100),
  currency: 'SAR',
  categoryId: catId('other'),
  walletId: 'w1',
  goalId: null,
  billId: null,
  merchantId: null,
  date: '2026-09-01',
  note: null,
  source: null,
  transferId: null,
  plannedId: null,
  createdAt: '',
  updatedAt: '',
  version: '',
  dirty: 0,
  deleted: 0,
  ...over,
})

export const setAside = (over: Partial<LocalSetAside> = {}): LocalSetAside => ({
  id: next('a'),
  goalId: 'g',
  billId: null,
  occurrence: null,
  source: 'wallet',
  walletId: 'w1',
  externalLabel: null,
  amount: m(100),
  currency: 'SAR',
  note: null,
  position: 0,
  date: '2026-09-01',
  plannedId: null,
  releasedAt: null,
  releasedById: null,
  movedByTransferId: null,
  createdAt: '',
  updatedAt: '',
  version: '',
  dirty: 0,
  deleted: 0,
  ...over,
})
