/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ImportRouteImport } from './routes/import'
import { Route as TransactionsRouteRouteImport } from './routes/transactions/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as PlanningRouteRouteImport } from './routes/planning/route'
import { Route as GoalsRouteRouteImport } from './routes/goals/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PlanningIndexRouteImport } from './routes/planning/index'
import { Route as GoalsIndexRouteImport } from './routes/goals/index'
import { Route as TransactionsViewRouteImport } from './routes/transactions/$view'
import { Route as SettingsPreferencesRouteImport } from './routes/settings/preferences'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsMerchantsRouteImport } from './routes/settings/merchants'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings/integrations'
import { Route as SettingsImportRouteImport } from './routes/settings/import'
import { Route as SettingsEmailSyncRouteImport } from './routes/settings/email-sync'
import { Route as SettingsDataRouteImport } from './routes/settings/data'
import { Route as SettingsCurrenciesRouteImport } from './routes/settings/currencies'
import { Route as SettingsCategoriesRouteImport } from './routes/settings/categories'
import { Route as SettingsArchivedRouteImport } from './routes/settings/archived'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as PlanningSectionRouteImport } from './routes/planning/$section'
import { Route as GoalsSectionRouteImport } from './routes/goals/$section'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as SettingsEmailSyncCallbackRouteImport } from './routes/settings_.email-sync.callback'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google.callback'

const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRouteRoute = TransactionsRouteRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRouteRoute = PlanningRouteRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRouteRoute = GoalsRouteRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TransactionsRouteRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const PlanningIndexRoute = PlanningIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlanningRouteRoute,
} as any)
const GoalsIndexRoute = GoalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GoalsRouteRoute,
} as any)
const TransactionsViewRoute = TransactionsViewRouteImport.update({
  id: '/$view',
  path: '/$view',
  getParentRoute: () => TransactionsRouteRoute,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsMerchantsRoute = SettingsMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsImportRoute = SettingsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsEmailSyncRoute = SettingsEmailSyncRouteImport.update({
  id: '/email-sync',
  path: '/email-sync',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsCurrenciesRoute = SettingsCurrenciesRouteImport.update({
  id: '/currencies',
  path: '/currencies',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsCategoriesRoute = SettingsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const PlanningSectionRoute = PlanningSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => PlanningRouteRoute,
} as any)
const GoalsSectionRoute = GoalsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => GoalsRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsEmailSyncCallbackRoute =
  SettingsEmailSyncCallbackRouteImport.update({
    id: '/settings_/email-sync/callback',
    path: '/settings/email-sync/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/goals': typeof GoalsRouteRouteWithChildren
  '/planning': typeof PlanningRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/transactions': typeof TransactionsRouteRouteWithChildren
  '/import': typeof ImportRoute
  '/reports': typeof ReportsRoute
  '/setup': typeof SetupRoute
  '/wallets': typeof WalletsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/goals/$section': typeof GoalsSectionRoute
  '/planning/$section': typeof PlanningSectionRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/currencies': typeof SettingsCurrenciesRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/email-sync': typeof SettingsEmailSyncRoute
  '/settings/import': typeof SettingsImportRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/merchants': typeof SettingsMerchantsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/transactions/$view': typeof TransactionsViewRoute
  '/goals/': typeof GoalsIndexRoute
  '/planning/': typeof PlanningIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/settings/email-sync/callback': typeof SettingsEmailSyncCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/reports': typeof ReportsRoute
  '/setup': typeof SetupRoute
  '/wallets': typeof WalletsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/goals/$section': typeof GoalsSectionRoute
  '/planning/$section': typeof PlanningSectionRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/currencies': typeof SettingsCurrenciesRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/email-sync': typeof SettingsEmailSyncRoute
  '/settings/import': typeof SettingsImportRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/merchants': typeof SettingsMerchantsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/transactions/$view': typeof TransactionsViewRoute
  '/goals': typeof GoalsIndexRoute
  '/planning': typeof PlanningIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/settings/email-sync/callback': typeof SettingsEmailSyncCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/goals': typeof GoalsRouteRouteWithChildren
  '/planning': typeof PlanningRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/transactions': typeof TransactionsRouteRouteWithChildren
  '/import': typeof ImportRoute
  '/reports': typeof ReportsRoute
  '/setup': typeof SetupRoute
  '/wallets': typeof WalletsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/goals/$section': typeof GoalsSectionRoute
  '/planning/$section': typeof PlanningSectionRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/currencies': typeof SettingsCurrenciesRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/email-sync': typeof SettingsEmailSyncRoute
  '/settings/import': typeof SettingsImportRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/merchants': typeof SettingsMerchantsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/transactions/$view': typeof TransactionsViewRoute
  '/goals/': typeof GoalsIndexRoute
  '/planning/': typeof PlanningIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/settings_/email-sync/callback': typeof SettingsEmailSyncCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/goals'
    | '/planning'
    | '/settings'
    | '/transactions'
    | '/import'
    | '/reports'
    | '/setup'
    | '/wallets'
    | '/auth/login'
    | '/auth/signup'
    | '/goals/$section'
    | '/planning/$section'
    | '/settings/account'
    | '/settings/archived'
    | '/settings/categories'
    | '/settings/currencies'
    | '/settings/data'
    | '/settings/email-sync'
    | '/settings/import'
    | '/settings/integrations'
    | '/settings/merchants'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/transactions/$view'
    | '/goals/'
    | '/planning/'
    | '/settings/'
    | '/transactions/'
    | '/auth/google/callback'
    | '/settings/email-sync/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/reports'
    | '/setup'
    | '/wallets'
    | '/auth/login'
    | '/auth/signup'
    | '/goals/$section'
    | '/planning/$section'
    | '/settings/account'
    | '/settings/archived'
    | '/settings/categories'
    | '/settings/currencies'
    | '/settings/data'
    | '/settings/email-sync'
    | '/settings/import'
    | '/settings/integrations'
    | '/settings/merchants'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/transactions/$view'
    | '/goals'
    | '/planning'
    | '/settings'
    | '/transactions'
    | '/auth/google/callback'
    | '/settings/email-sync/callback'
  id:
    | '__root__'
    | '/'
    | '/goals'
    | '/planning'
    | '/settings'
    | '/transactions'
    | '/import'
    | '/reports'
    | '/setup'
    | '/wallets'
    | '/auth/login'
    | '/auth/signup'
    | '/goals/$section'
    | '/planning/$section'
    | '/settings/account'
    | '/settings/archived'
    | '/settings/categories'
    | '/settings/currencies'
    | '/settings/data'
    | '/settings/email-sync'
    | '/settings/import'
    | '/settings/integrations'
    | '/settings/merchants'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/transactions/$view'
    | '/goals/'
    | '/planning/'
    | '/settings/'
    | '/transactions/'
    | '/auth/google/callback'
    | '/settings_/email-sync/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GoalsRouteRoute: typeof GoalsRouteRouteWithChildren
  PlanningRouteRoute: typeof PlanningRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  TransactionsRouteRoute: typeof TransactionsRouteRouteWithChildren
  ImportRoute: typeof ImportRoute
  ReportsRoute: typeof ReportsRoute
  SetupRoute: typeof SetupRoute
  WalletsRoute: typeof WalletsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  SettingsEmailSyncCallbackRoute: typeof SettingsEmailSyncCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof TransactionsRouteRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/planning/': {
      id: '/planning/'
      path: '/'
      fullPath: '/planning/'
      preLoaderRoute: typeof PlanningIndexRouteImport
      parentRoute: typeof PlanningRouteRoute
    }
    '/goals/': {
      id: '/goals/'
      path: '/'
      fullPath: '/goals/'
      preLoaderRoute: typeof GoalsIndexRouteImport
      parentRoute: typeof GoalsRouteRoute
    }
    '/transactions/$view': {
      id: '/transactions/$view'
      path: '/$view'
      fullPath: '/transactions/$view'
      preLoaderRoute: typeof TransactionsViewRouteImport
      parentRoute: typeof TransactionsRouteRoute
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/merchants': {
      id: '/settings/merchants'
      path: '/merchants'
      fullPath: '/settings/merchants'
      preLoaderRoute: typeof SettingsMerchantsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/import': {
      id: '/settings/import'
      path: '/import'
      fullPath: '/settings/import'
      preLoaderRoute: typeof SettingsImportRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/email-sync': {
      id: '/settings/email-sync'
      path: '/email-sync'
      fullPath: '/settings/email-sync'
      preLoaderRoute: typeof SettingsEmailSyncRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/currencies': {
      id: '/settings/currencies'
      path: '/currencies'
      fullPath: '/settings/currencies'
      preLoaderRoute: typeof SettingsCurrenciesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/categories': {
      id: '/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof SettingsCategoriesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/planning/$section': {
      id: '/planning/$section'
      path: '/$section'
      fullPath: '/planning/$section'
      preLoaderRoute: typeof PlanningSectionRouteImport
      parentRoute: typeof PlanningRouteRoute
    }
    '/goals/$section': {
      id: '/goals/$section'
      path: '/$section'
      fullPath: '/goals/$section'
      preLoaderRoute: typeof GoalsSectionRouteImport
      parentRoute: typeof GoalsRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/email-sync/callback': {
      id: '/settings_/email-sync/callback'
      path: '/settings/email-sync/callback'
      fullPath: '/settings/email-sync/callback'
      preLoaderRoute: typeof SettingsEmailSyncCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GoalsRouteRouteChildren {
  GoalsSectionRoute: typeof GoalsSectionRoute
  GoalsIndexRoute: typeof GoalsIndexRoute
}

const GoalsRouteRouteChildren: GoalsRouteRouteChildren = {
  GoalsSectionRoute: GoalsSectionRoute,
  GoalsIndexRoute: GoalsIndexRoute,
}

const GoalsRouteRouteWithChildren = GoalsRouteRoute._addFileChildren(
  GoalsRouteRouteChildren,
)

interface PlanningRouteRouteChildren {
  PlanningSectionRoute: typeof PlanningSectionRoute
  PlanningIndexRoute: typeof PlanningIndexRoute
}

const PlanningRouteRouteChildren: PlanningRouteRouteChildren = {
  PlanningSectionRoute: PlanningSectionRoute,
  PlanningIndexRoute: PlanningIndexRoute,
}

const PlanningRouteRouteWithChildren = PlanningRouteRoute._addFileChildren(
  PlanningRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsCategoriesRoute: typeof SettingsCategoriesRoute
  SettingsCurrenciesRoute: typeof SettingsCurrenciesRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsEmailSyncRoute: typeof SettingsEmailSyncRoute
  SettingsImportRoute: typeof SettingsImportRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsMerchantsRoute: typeof SettingsMerchantsRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsCategoriesRoute: SettingsCategoriesRoute,
  SettingsCurrenciesRoute: SettingsCurrenciesRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsEmailSyncRoute: SettingsEmailSyncRoute,
  SettingsImportRoute: SettingsImportRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsMerchantsRoute: SettingsMerchantsRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface TransactionsRouteRouteChildren {
  TransactionsViewRoute: typeof TransactionsViewRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

const TransactionsRouteRouteChildren: TransactionsRouteRouteChildren = {
  TransactionsViewRoute: TransactionsViewRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}

const TransactionsRouteRouteWithChildren =
  TransactionsRouteRoute._addFileChildren(TransactionsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GoalsRouteRoute: GoalsRouteRouteWithChildren,
  PlanningRouteRoute: PlanningRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  TransactionsRouteRoute: TransactionsRouteRouteWithChildren,
  ImportRoute: ImportRoute,
  ReportsRoute: ReportsRoute,
  SetupRoute: SetupRoute,
  WalletsRoute: WalletsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  SettingsEmailSyncCallbackRoute: SettingsEmailSyncCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
