/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ImportRouteImport } from './routes/import'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as BalancesRouteImport } from './routes/balances'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsPreferencesRouteImport } from './routes/settings/preferences'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsMerchantsRouteImport } from './routes/settings/merchants'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings/integrations'
import { Route as SettingsEmailSyncRouteImport } from './routes/settings/email-sync'
import { Route as SettingsDataRouteImport } from './routes/settings/data'
import { Route as SettingsCurrenciesRouteImport } from './routes/settings/currencies'
import { Route as SettingsCategoriesRouteImport } from './routes/settings/categories'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as SettingsEmailSyncCallbackRouteImport } from './routes/settings_.email-sync.callback'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google.callback'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const BalancesRoute = BalancesRouteImport.update({
  id: '/balances',
  path: '/balances',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsMerchantsRoute = SettingsMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsEmailSyncRoute = SettingsEmailSyncRouteImport.update({
  id: '/email-sync',
  path: '/email-sync',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsCurrenciesRoute = SettingsCurrenciesRouteImport.update({
  id: '/currencies',
  path: '/currencies',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsCategoriesRoute = SettingsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsEmailSyncCallbackRoute =
  SettingsEmailSyncCallbackRouteImport.update({
    id: '/settings_/email-sync/callback',
    path: '/settings/email-sync/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/balances': typeof BalancesRoute
  '/goals': typeof GoalsRoute
  '/import': typeof ImportRoute
  '/transactions': typeof TransactionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/currencies': typeof SettingsCurrenciesRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/email-sync': typeof SettingsEmailSyncRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/merchants': typeof SettingsMerchantsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/': typeof SettingsIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/settings/email-sync/callback': typeof SettingsEmailSyncCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/balances': typeof BalancesRoute
  '/goals': typeof GoalsRoute
  '/import': typeof ImportRoute
  '/transactions': typeof TransactionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/currencies': typeof SettingsCurrenciesRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/email-sync': typeof SettingsEmailSyncRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/merchants': typeof SettingsMerchantsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings': typeof SettingsIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/settings/email-sync/callback': typeof SettingsEmailSyncCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/balances': typeof BalancesRoute
  '/goals': typeof GoalsRoute
  '/import': typeof ImportRoute
  '/transactions': typeof TransactionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/currencies': typeof SettingsCurrenciesRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/email-sync': typeof SettingsEmailSyncRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/merchants': typeof SettingsMerchantsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/': typeof SettingsIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/settings_/email-sync/callback': typeof SettingsEmailSyncCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/balances'
    | '/goals'
    | '/import'
    | '/transactions'
    | '/auth/login'
    | '/auth/signup'
    | '/settings/account'
    | '/settings/categories'
    | '/settings/currencies'
    | '/settings/data'
    | '/settings/email-sync'
    | '/settings/integrations'
    | '/settings/merchants'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/settings/'
    | '/auth/google/callback'
    | '/settings/email-sync/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/balances'
    | '/goals'
    | '/import'
    | '/transactions'
    | '/auth/login'
    | '/auth/signup'
    | '/settings/account'
    | '/settings/categories'
    | '/settings/currencies'
    | '/settings/data'
    | '/settings/email-sync'
    | '/settings/integrations'
    | '/settings/merchants'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/settings'
    | '/auth/google/callback'
    | '/settings/email-sync/callback'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/balances'
    | '/goals'
    | '/import'
    | '/transactions'
    | '/auth/login'
    | '/auth/signup'
    | '/settings/account'
    | '/settings/categories'
    | '/settings/currencies'
    | '/settings/data'
    | '/settings/email-sync'
    | '/settings/integrations'
    | '/settings/merchants'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/settings/'
    | '/auth/google/callback'
    | '/settings_/email-sync/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  BalancesRoute: typeof BalancesRoute
  GoalsRoute: typeof GoalsRoute
  ImportRoute: typeof ImportRoute
  TransactionsRoute: typeof TransactionsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  SettingsEmailSyncCallbackRoute: typeof SettingsEmailSyncCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balances': {
      id: '/balances'
      path: '/balances'
      fullPath: '/balances'
      preLoaderRoute: typeof BalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/merchants': {
      id: '/settings/merchants'
      path: '/merchants'
      fullPath: '/settings/merchants'
      preLoaderRoute: typeof SettingsMerchantsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/email-sync': {
      id: '/settings/email-sync'
      path: '/email-sync'
      fullPath: '/settings/email-sync'
      preLoaderRoute: typeof SettingsEmailSyncRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/currencies': {
      id: '/settings/currencies'
      path: '/currencies'
      fullPath: '/settings/currencies'
      preLoaderRoute: typeof SettingsCurrenciesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/categories': {
      id: '/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof SettingsCategoriesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/email-sync/callback': {
      id: '/settings_/email-sync/callback'
      path: '/settings/email-sync/callback'
      fullPath: '/settings/email-sync/callback'
      preLoaderRoute: typeof SettingsEmailSyncCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsCategoriesRoute: typeof SettingsCategoriesRoute
  SettingsCurrenciesRoute: typeof SettingsCurrenciesRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsEmailSyncRoute: typeof SettingsEmailSyncRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsMerchantsRoute: typeof SettingsMerchantsRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsCategoriesRoute: SettingsCategoriesRoute,
  SettingsCurrenciesRoute: SettingsCurrenciesRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsEmailSyncRoute: SettingsEmailSyncRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsMerchantsRoute: SettingsMerchantsRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  BalancesRoute: BalancesRoute,
  GoalsRoute: GoalsRoute,
  ImportRoute: ImportRoute,
  TransactionsRoute: TransactionsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  SettingsEmailSyncCallbackRoute: SettingsEmailSyncCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
