/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as BalancesRouteImport } from './routes/balances'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as SettingsEmailSyncCallbackRouteImport } from './routes/settings_.email-sync.callback'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google.callback'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const BalancesRoute = BalancesRouteImport.update({
  id: '/balances',
  path: '/balances',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsEmailSyncCallbackRoute =
  SettingsEmailSyncCallbackRouteImport.update({
    id: '/settings_/email-sync/callback',
    path: '/settings/email-sync/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/balances': typeof BalancesRoute
  '/goals': typeof GoalsRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/settings/email-sync/callback': typeof SettingsEmailSyncCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/balances': typeof BalancesRoute
  '/goals': typeof GoalsRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/settings/email-sync/callback': typeof SettingsEmailSyncCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/balances': typeof BalancesRoute
  '/goals': typeof GoalsRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/settings_/email-sync/callback': typeof SettingsEmailSyncCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/balances'
    | '/goals'
    | '/settings'
    | '/transactions'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/google/callback'
    | '/settings/email-sync/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/balances'
    | '/goals'
    | '/settings'
    | '/transactions'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/google/callback'
    | '/settings/email-sync/callback'
  id:
    | '__root__'
    | '/'
    | '/balances'
    | '/goals'
    | '/settings'
    | '/transactions'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/google/callback'
    | '/settings_/email-sync/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BalancesRoute: typeof BalancesRoute
  GoalsRoute: typeof GoalsRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  SettingsEmailSyncCallbackRoute: typeof SettingsEmailSyncCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balances': {
      id: '/balances'
      path: '/balances'
      fullPath: '/balances'
      preLoaderRoute: typeof BalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/email-sync/callback': {
      id: '/settings_/email-sync/callback'
      path: '/settings/email-sync/callback'
      fullPath: '/settings/email-sync/callback'
      preLoaderRoute: typeof SettingsEmailSyncCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BalancesRoute: BalancesRoute,
  GoalsRoute: GoalsRoute,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  SettingsEmailSyncCallbackRoute: SettingsEmailSyncCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
