// GENERATED FILE — do not edit by hand.
// Run `pnpm generate-config` after any change to the backend's currency seed.
//
// The offline/first-run floor for the app config: the client starts from this snapshot,
// then prefers the cached Dexie row and finally a fresh `GET /config`. Rates here are the
// static deploy seed; a user's own overrides always win over them.
import type { AppConfig, CurrencyMeta } from './appConfig'

const CURRENCIES: CurrencyMeta[] = [
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', minorUnit: 2 },
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', minorUnit: 2 },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'L', minorUnit: 2 },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏', minorUnit: 2 },
  {
    code: 'ANG',
    name: 'Netherlands Antillean Guilder',
    symbol: 'ƒ',
    minorUnit: 2,
  },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', minorUnit: 2 },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$', minorUnit: 2 },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', minorUnit: 2 },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', minorUnit: 2 },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', minorUnit: 2 },
  {
    code: 'BAM',
    name: 'Bosnia-Herzegovina Convertible Mark',
    symbol: 'KM',
    minorUnit: 2,
  },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: '$', minorUnit: 2 },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', minorUnit: 2 },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', minorUnit: 2 },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: 'BD', minorUnit: 3 },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', minorUnit: 0 },
  { code: 'BMD', name: 'Bermudian Dollar', symbol: '$', minorUnit: 2 },
  { code: 'BND', name: 'Brunei Dollar', symbol: 'B$', minorUnit: 2 },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs', minorUnit: 2 },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', minorUnit: 2 },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: '$', minorUnit: 2 },
  { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', minorUnit: 2 },
  { code: 'BWP', name: 'Botswanan Pula', symbol: 'P', minorUnit: 2 },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', minorUnit: 2 },
  { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$', minorUnit: 2 },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', minorUnit: 2 },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', minorUnit: 2 },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', minorUnit: 2 },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$', minorUnit: 0 },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', minorUnit: 2 },
  { code: 'COP', name: 'Colombian Peso', symbol: '$', minorUnit: 2 },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', minorUnit: 2 },
  { code: 'CUP', name: 'Cuban Peso', symbol: '$', minorUnit: 2 },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$', minorUnit: 2 },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', minorUnit: 2 },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', minorUnit: 0 },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', minorUnit: 2 },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', minorUnit: 2 },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج', minorUnit: 2 },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', minorUnit: 2 },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', minorUnit: 2 },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', minorUnit: 2 },
  { code: 'EUR', name: 'Euro', symbol: '€', minorUnit: 2 },
  { code: 'FJD', name: 'Fijian Dollar', symbol: 'FJ$', minorUnit: 2 },
  { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£', minorUnit: 2 },
  { code: 'GBP', name: 'British Pound', symbol: '£', minorUnit: 2 },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾', minorUnit: 2 },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵', minorUnit: 2 },
  { code: 'GIP', name: 'Gibraltar Pound', symbol: '£', minorUnit: 2 },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', minorUnit: 2 },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', minorUnit: 0 },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', minorUnit: 2 },
  { code: 'GYD', name: 'Guyanaese Dollar', symbol: 'G$', minorUnit: 2 },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', minorUnit: 2 },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', minorUnit: 2 },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', minorUnit: 2 },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', minorUnit: 2 },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', minorUnit: 2 },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', minorUnit: 2 },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', minorUnit: 3 },
  { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', minorUnit: 2 },
  { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr', minorUnit: 0 },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', minorUnit: 2 },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'JD', minorUnit: 3 },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', minorUnit: 0 },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', minorUnit: 2 },
  { code: 'KGS', name: 'Kyrgystani Som', symbol: 'с', minorUnit: 2 },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', minorUnit: 2 },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', minorUnit: 0 },
  { code: 'KPW', name: 'North Korean Won', symbol: '₩', minorUnit: 2 },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', minorUnit: 0 },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'KD', minorUnit: 3 },
  { code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$', minorUnit: 2 },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', minorUnit: 2 },
  { code: 'LAK', name: 'Laotian Kip', symbol: '₭', minorUnit: 2 },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل', minorUnit: 2 },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', minorUnit: 2 },
  { code: 'LRD', name: 'Liberian Dollar', symbol: 'L$', minorUnit: 2 },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'L', minorUnit: 2 },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'LD', minorUnit: 3 },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.', minorUnit: 2 },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', minorUnit: 2 },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', minorUnit: 2 },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', minorUnit: 2 },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', minorUnit: 2 },
  { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', minorUnit: 2 },
  { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP$', minorUnit: 2 },
  { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM', minorUnit: 2 },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', minorUnit: 2 },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf', minorUnit: 2 },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', minorUnit: 2 },
  { code: 'MXN', name: 'Mexican Peso', symbol: '$', minorUnit: 2 },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', minorUnit: 2 },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', minorUnit: 2 },
  { code: 'NAD', name: 'Namibian Dollar', symbol: 'N$', minorUnit: 2 },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', minorUnit: 2 },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', minorUnit: 2 },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', minorUnit: 2 },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: 'रू', minorUnit: 2 },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', minorUnit: 2 },
  { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.', minorUnit: 3 },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', minorUnit: 2 },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', minorUnit: 2 },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', minorUnit: 2 },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', minorUnit: 2 },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', minorUnit: 2 },
  { code: 'PLN', name: 'Polish Złoty', symbol: 'zł', minorUnit: 2 },
  { code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲', minorUnit: 0 },
  { code: 'QAR', name: 'Qatari Riyal', symbol: 'ر.ق', minorUnit: 2 },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', minorUnit: 2 },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин', minorUnit: 2 },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', minorUnit: 2 },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'FRw', minorUnit: 0 },
  { code: 'SAR', name: 'Saudi Riyal', symbol: 'SR', minorUnit: 2 },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SI$', minorUnit: 2 },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', minorUnit: 2 },
  { code: 'SDG', name: 'Sudanese Pound', symbol: 'ج.س', minorUnit: 2 },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', minorUnit: 2 },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', minorUnit: 2 },
  { code: 'SHP', name: 'Saint Helena Pound', symbol: '£', minorUnit: 2 },
  { code: 'SLE', name: 'Sierra Leonean Leone', symbol: 'Le', minorUnit: 2 },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'Sh', minorUnit: 2 },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: '$', minorUnit: 2 },
  { code: 'SSP', name: 'South Sudanese Pound', symbol: '£', minorUnit: 2 },
  {
    code: 'STN',
    name: 'São Tomé & Príncipe Dobra',
    symbol: 'Db',
    minorUnit: 2,
  },
  { code: 'SYP', name: 'Syrian Pound', symbol: '£S', minorUnit: 2 },
  { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'L', minorUnit: 2 },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', minorUnit: 2 },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'ЅМ', minorUnit: 2 },
  { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'm', minorUnit: 2 },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'DT', minorUnit: 3 },
  { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', minorUnit: 2 },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', minorUnit: 2 },
  {
    code: 'TTD',
    name: 'Trinidad & Tobago Dollar',
    symbol: 'TT$',
    minorUnit: 2,
  },
  { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', minorUnit: 2 },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', minorUnit: 2 },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', minorUnit: 2 },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', minorUnit: 0 },
  { code: 'USD', name: 'US Dollar', symbol: '$', minorUnit: 2 },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', minorUnit: 2 },
  { code: 'UZS', name: 'Uzbekistani Som', symbol: 'soʼm', minorUnit: 2 },
  { code: 'VES', name: 'Venezuelan Bolívar', symbol: 'Bs', minorUnit: 2 },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', minorUnit: 0 },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', minorUnit: 0 },
  { code: 'WST', name: 'Samoan Tala', symbol: 'T', minorUnit: 2 },
  {
    code: 'XAF',
    name: 'Central African CFA Franc',
    symbol: 'FCFA',
    minorUnit: 0,
  },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: 'EC$', minorUnit: 2 },
  { code: 'XCG', name: 'Caribbean Guilder', symbol: 'Cg', minorUnit: 2 },
  { code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA', minorUnit: 0 },
  { code: 'XPF', name: 'CFP Franc', symbol: '₣', minorUnit: 0 },
  { code: 'YER', name: 'Yemeni Rial', symbol: '﷼', minorUnit: 2 },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', minorUnit: 2 },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', minorUnit: 2 },
  { code: 'ZWG', name: 'Zimbabwe Gold', symbol: 'ZiG', minorUnit: 2 },
]

const RATES: Record<string, number> = {
  AED: 1.02,
  AFN: 0.0543478,
  ALL: 0.0407609,
  AMD: 0.00974026,
  ANG: 2.09497,
  AOA: 0.00407609,
  ARS: 0.00267857,
  AUD: 2.45098,
  AWG: 2.09497,
  AZN: 2.20588,
  BAM: 2.08333,
  BBD: 1.875,
  BDT: 0.0307377,
  BGN: 2.08333,
  BHD: 9.9734,
  BIF: 0.00127119,
  BMD: 3.75,
  BND: 2.88462,
  BOB: 0.542692,
  BRL: 0.694444,
  BSD: 3.75,
  BTN: 0.0426136,
  BWP: 0.275735,
  BYN: 1.14679,
  BZD: 1.875,
  CAD: 2.71739,
  CDF: 0.00131579,
  CHF: 4.6875,
  CLP: 0.00394737,
  CNY: 0.528169,
  COP: 0.000961538,
  CRC: 0.00742574,
  CVE: 0.0369458,
  CZK: 0.178571,
  DJF: 0.0210674,
  DKK: 0.585938,
  DOP: 0.0604839,
  DZD: 0.0288462,
  EGP: 0.078125,
  ERN: 0.25,
  ETB: 0.0277778,
  EUR: 4.05,
  FJD: 1.66667,
  FKP: 5.06757,
  GBP: 4.75,
  GEL: 1.38889,
  GHS: 0.340909,
  GIP: 5.06757,
  GMD: 0.0520833,
  GNF: 0.000431034,
  GTQ: 0.487013,
  GYD: 0.0179426,
  HKD: 0.482005,
  HNL: 0.14313,
  HTG: 0.028626,
  HUF: 0.0105634,
  IDR: 0.000230061,
  INR: 0.0426136,
  IQD: 0.0028626,
  ISK: 0.03,
  JMD: 0.0237342,
  JOD: 5.28914,
  JPY: 0.0246711,
  KES: 0.0290698,
  KGS: 0.0431034,
  KHR: 0.000925926,
  KMF: 0.00846501,
  KRW: 0.00267857,
  KWD: 12.2549,
  KYD: 4.5018,
  KZT: 0.00721154,
  LAK: 0.000172811,
  LBP: 0.0000418994,
  LKR: 0.0125,
  LRD: 0.0197368,
  LSL: 0.215517,
  LYD: 0.688073,
  MAD: 0.403226,
  MDL: 0.214286,
  MGA: 0.000833333,
  MKD: 0.0669643,
  MMK: 0.00178571,
  MNT: 0.00107143,
  MOP: 0.468165,
  MRU: 0.0942211,
  MUR: 0.0815217,
  MVR: 0.243506,
  MWK: 0.00216138,
  MXN: 0.202703,
  MYR: 0.882353,
  MZN: 0.0586854,
  NAD: 0.215517,
  NGN: 0.00253378,
  NIO: 0.101902,
  NOK: 0.357143,
  NPR: 0.0265957,
  NZD: 2.23214,
  OMR: 9.75293,
  PAB: 3.75,
  PEN: 1.07143,
  PGK: 0.925926,
  PHP: 0.0646552,
  PKR: 0.0133929,
  PLN: 1.01351,
  PYG: 0.000493421,
  QAR: 1.03022,
  RON: 0.824176,
  RSD: 0.0353774,
  RUB: 0.0457317,
  RWF: 0.00260417,
  SAR: 1,
  SBD: 0.446429,
  SCR: 0.262238,
  SDG: 0.0062396,
  SEK: 0.390625,
  SGD: 2.88462,
  SHP: 5.06757,
  SLE: 0.166667,
  SOS: 0.00656743,
  SRD: 0.0986842,
  STN: 0.166667,
  SZL: 0.215517,
  THB: 0.115385,
  TJS: 0.398936,
  TMT: 1.07143,
  TND: 1.27119,
  TOP: 1.57563,
  TRY: 0.0914634,
  TTD: 0.553097,
  TWD: 0.119048,
  TZS: 0.0015121,
  UAH: 0.0903614,
  UGX: 0.00104167,
  USD: 3.75,
  UYU: 0.09375,
  UZS: 0.0003,
  VND: 0.000142586,
  VUV: 0.03125,
  WST: 1.36364,
  XAF: 0.00617792,
  XCD: 1.38889,
  XCG: 2.09497,
  XOF: 0.00617792,
  XPF: 0.0339367,
  YER: 0.0153061,
  ZAR: 0.215517,
  ZMW: 0.159574,
}

export const BUNDLED_CONFIG: AppConfig = {
  version: '2026-09-22.1',
  currencies: CURRENCIES,
  rates: RATES,
  defaultBaseCurrency: 'SAR',
  limits: {
    importMaxRows: 50000,
    importMaxBytes: 10485760,
    emailSyncMaxLookbackDays: 180,
    emailSyncMaxLimit: 200,
    emailRulesMax: 20,
    emailRuleSamplesMax: 50,
    emailRuleSendersMax: 10,
    emailRuleTermsMax: 10,
    transactionBulkMax: 1000,
    integrationKeysMax: 20,
    integrationRulesMax: 10,
    integrationPayloadMaxBytes: 65536,
    plannedBulkMax: 200,
    plannedMax: 5000,
  },
  integrations: {
    webhookUrl: null,
    webhookPath: '/api/v1/webhooks/transactions',
  },
}
